export const categories = [
    { id: 'all', name: 'All Games', icon: '🎮' },
    { id: 'racing', name: 'Racing', icon: '🏎️' },
    { id: 'shooting', name: 'Shooting', icon: '🎯' },
    { id: 'adventure', name: 'Adventure', icon: '⚔️' },
    { id: 'strategy', name: 'Strategy', icon: '♟️' },
    { id: 'sports', name: 'Sports', icon: '⚡' },
    { id: 'horror', name: 'Horror', icon: '👻' },
    { id: 'puzzle', name: 'Puzzle', icon: '🧩' },
]

export const games = [
    {
        id: 'night-rush',
        title: 'Night Rush',
        subtitle: 'Arcade Racing',
        category: 'Racing',
        image: '/game-night-rush.png',
        rating: 4.8,
        players: '2.4M',
        playUrl: 'https://slowroads.io/',
    },
    {
        id: 'void-strike',
        title: 'Void Strike',
        subtitle: 'Line Force Protocol',
        category: 'Shooting',
        image: '/game-void-strike.png',
        rating: 4.9,
        players: '5.1M',
        playUrl: 'https://api.v6.panalapp.com/games/slope/',
    },
    {
        id: 'auroras-veil',
        title: "Aurora's Veil",
        subtitle: 'Ancient Realms',
        category: 'Adventure',
        image: '/game-auroras-veil.png',
        rating: 4.7,
        players: '1.8M',
        playUrl: 'https://hexgl.bkcore.com/play/',
    },
    {
        id: 'command-nexus',
        title: 'Command Nexus',
        subtitle: 'Strategy Ascendant',
        category: 'Strategy',
        image: '/game-command-nexus.png',
        rating: 4.6,
        players: '980K',
        playUrl: 'https://hexgl.bkcore.com/play/',
    },
    {
        id: 'neon-stride',
        title: 'Neon Stride',
        subtitle: 'Cyber League',
        category: 'Sports',
        image: '/game-neon-stride.png',
        rating: 4.5,
        players: '1.2M',
        playUrl: 'https://api.v6.panalapp.com/games/slope/',
    },
    {
        id: 'abyss-whispers',
        title: 'Abyss Whispers',
        subtitle: 'A Survival Horror Experience',
        category: 'Horror',
        image: '/game-abyss-whispers.png',
        rating: 4.8,
        players: '620K',
        playUrl: 'https://slowroads.io/',
    },
    {
        id: 'nexus-shift',
        title: 'Nexus Shift',
        subtitle: 'A 3D Puzzle Adventure',
        category: 'Puzzle',
        image: '/game-nexus-shift.png',
        rating: 4.7,
        players: '890K',
        playUrl: 'https://hexgl.bkcore.com/play/',
    },
    {
        id: 'night-rush-2',
        title: 'Night Rush II',
        subtitle: 'Turbo Edition',
        category: 'Racing',
        image: '/game-night-rush.png',
        rating: 4.6,
        players: '1.5M',
        playUrl: 'https://slowroads.io/',
    },
]